vich_uploader:
    db_driver: orm

    mappings:
        producto_image:
            uri_prefix: /imgs/productos/vichimg
            upload_destination: '%kernel.project_dir%/public/imgs/productos/vichimg'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

